--- #YAML:1.0
name: DateTime-Format-ICal
version: 0.05
license: perl
distribution_type: module
requires:
  DateTime: 0.1
  DateTime::Event::ICal: 0
  DateTime::Span: 0
  DateTime::TimeZone: 0.17
  Params::Validate: 0.59
recommends: {}
build_requires: {}
conflicts: {}
provides:
  DateTime::Format::ICal:
    file: lib/DateTime/Format/ICal.pm
    version: 0.05
generated_by: Module::Build version 0.18
