--- #YAML:1.0
name: DateTime-Format-ICal
version: 0.04
license: perl
distribution_type: module
requires:
  DateTime: 0.1
recommends: {}
build_requires: {}
conflicts: {}
provides:
  DateTime::Format::ICal:
    file: lib/DateTime/Format/ICal.pm
    version: 0.04
generated_by: Module::Build version 0.18
